### ISSUE TITLE
command from readme don't work

### ISSUE THREAD

**Issue by centralhardware** [vjFaLk/firefly-bot#2]
`5 Starbucks Coffee Food`

command with three parameter from readme don't work, 1,2 work fine.

firefly iii version: 5.3.0
bot version: latest docker image

**Comment by vjFaLk** [comment]
Hey @centralhardware, sorry for taking so long to reply to this, but I just pushed a new update with a bunch of new features and fixes. Please check out the [Changelog](https://github.com/vjFaLk/firefly-bot/releases/tag/v0.0.2). I didn't notice your issue with the previous version either? But do try out this version.
